export enum FootballPositions {
  DEFAULT = "",

  // Defensive Positions
  GK = "Goalkeeper",
  CB = "Center Back",
  CH = "Center Half",
  LB = "Left Back",
  LCB = "Left Center Back",
  LH = "Left Half",
  LWB = "Left Wing Back",
  OB = "Outside Back",
  RB = "Right Back",
  RCB = "Right Center Back",
  RWB = "Right Wing Back",
  SW = "Sweeper",
  WB = "Wing Back",

  // Midfield Positions
  AM = "Attacking Midfielder",
  AMC = "Attacking Midfielder Center",
  AMF = "Attacking Midfielder",
  AML = "Attacking Midfielder Left",
  AMR = "Attacking Midfielder Right",
  CAM = "Central Attacking Midfielder",
  CDM = "Central Defensive Midfielder",
  CM = "Central Midfield",
  CMF = "Central Midfielder",
  DM = "Defensive Midfielder",
  LM = "Left Midfielder",
  LW = "Left Winger",
  M = "Midfielder",
  RM = "Right Midfielder",
  RW = "Right Winger",

  // Forward Positions
  CF = "Center Forward",
  LF = "Left Forward",
  LS = "Left Striker",
  RF = "Right Forward",
  RS = "Right Striker",
  SS = "Second Striker",
  ST = "Striker",
  WF = "Wing Forward",
}

export enum FootballPositionsAbbreviations {
  DEFAULT = "",

  // Defensive Positions
  GK = "GK",
  CB = "CB",
  CH = "CH",
  LB = "LB",
  LCB = "LCB",
  LH = "LH",
  LWB = "LWB",
  OB = "OB",
  RB = "RB",
  RCB = "RCB",
  RWB = "RWB",
  SW = "SW",
  WB = "WB",

  // Midfield Positions
  AM = "AM",
  AMC = "AMC",
  AMF = "AMF",
  AML = "AML",
  AMR = "AMR",
  CAM = "CAM",
  CDM = "CDM",
  CM = "CM",
  CMF = "CMF",
  DM = "DM",
  LM = "LM",
  LW = "LW",
  M = "M",
  RM = "RM",
  RW = "RW",

  // Forward Positions
  CF = "CF",
  LF = "LF",
  LS = "LS",
  RF = "RF",
  RS = "RS",
  SS = "SS",
  ST = "ST",
  WF = "WF",
}
